// Copyright 2020-2025 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by gnark DO NOT EDIT

package bls12381

import (
	"errors"
	"fmt"

	"github.com/consensys/gnark-crypto/ecc"
	curve "github.com/consensys/gnark-crypto/ecc/bls12-381"
	"github.com/consensys/gnark-crypto/ecc/bls12-381/fr"

	// groth16_bls12381 "github.com/consensys/gnark/backend/groth16/bls12-381"
	// fr_bls12381 "github.com/consensys/gnark-crypto/ecc/bls12-381/fr"

	groth16_bls12381 "github.com/consensys/gnark/backend/groth16/bls12-381"
)

var (
	errPairingCheckFailed         = errors.New("pairing doesn't match")
	errCorrectSubgroupCheckFailed = errors.New("points in the proof are not in the correct subgroup")
)

type PreparedVKParams struct {
	e        curve.GT
	deltaNeg curve.G2Affine
	gammaNeg curve.G2Affine
}

func isValid(proof *groth16_bls12381.Proof) bool {
	return proof.Ar.IsInSubGroup() && proof.Krs.IsInSubGroup() && proof.Bs.IsInSubGroup()
}

func PrecomputeVKParams(vk *groth16_bls12381.VerifyingKey) (*PreparedVKParams, error) {
	var params PreparedVKParams
	var err error

	params.e, err = curve.Pair([]curve.G1Affine{vk.G1.Alpha}, []curve.G2Affine{vk.G2.Beta})
	if err != nil {
		return nil, err
	}

	params.deltaNeg.Neg(&vk.G2.Delta)
	params.gammaNeg.Neg(&vk.G2.Gamma)

	return &params, nil
}

// compute e(Σx.[Kvk(t)]1, -[γ]2)
func PreparePublicInputs(vk *groth16_bls12381.VerifyingKey, publicWitness fr.Vector) (*curve.G1Jac, error) {
	var kSum curve.G1Jac
	nbPublicVars := len(vk.G1.K) - len(vk.PublicAndCommitmentCommitted)

	if len(publicWitness) != nbPublicVars-1 {
		return nil, fmt.Errorf("invalid witness size, got %d, expected %d (public - ONE_WIRE)", len(publicWitness), len(vk.G1.K)-1)
	}

	if _, err := kSum.MultiExp(vk.G1.K[1:], publicWitness, ecc.MultiExpConfig{}); err != nil {
		return nil, err
	}

	return &kSum, nil
}

func VerifyPrepared(proof *groth16_bls12381.Proof, vk *groth16_bls12381.VerifyingKey, preparedPublicWitness *curve.G1Jac, params *PreparedVKParams) error {
	// check that the points in the proof are in the correct subgroup
	if !isValid(proof) {
		return errCorrectSubgroupCheckFailed
	}

	var doubleML curve.GT
	chDone := make(chan error, 1)

	// compute (eKrsδ, eArBs)
	go func() {
		var errML error
		doubleML, errML = curve.MillerLoop([]curve.G1Affine{proof.Krs, proof.Ar}, []curve.G2Affine{params.deltaNeg, proof.Bs})
		chDone <- errML
		close(chDone)
	}()

	prepared := curve.G1Jac{}
	prepared.Set(preparedPublicWitness)

	prepared.AddMixed(&vk.G1.K[0])

	for i := range proof.Commitments {
		prepared.AddMixed(&proof.Commitments[i])
	}

	var kSumAff curve.G1Affine
	kSumAff.FromJacobian(&prepared)

	right, err := curve.MillerLoop([]curve.G1Affine{kSumAff}, []curve.G2Affine{params.gammaNeg})
	if err != nil {
		return err
	}

	// wait for (eKrsδ, eArBs)
	if err := <-chDone; err != nil {
		return err
	}

	right = curve.FinalExponentiation(&right, &doubleML)
	if !params.e.Equal(&right) {
		return errPairingCheckFailed
	}

	return nil

}
