name: Go

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v6
        with:
          path: main

      - name: Checkout gnark-precomputes
        uses: actions/checkout@v6
        with:
          repository: akakou/gnark-precomputes
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: gnark-precomputes

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Test
        working-directory: main
        run: go test -v ./test

      - name: Bench
        working-directory: main
        run: cd ./bench && go run ./latency/baseline